language: node_js

git:
  depth: 3

stages:
  - deploy

jobs:
  include:
    - stage: deploy
      name: "Deploy to gh-pages"
      if: branch = main
      script:
        - git clone --depth=1 --branch=gh-pages https://github.com/w3c/dpub-aria.git gh-pages
        - rm -rf gh-pages/common gh-pages/img  
        - cp -R common img gh-pages
        - curl https://labs.w3.org/spec-generator/?type=respec"&"url=https://raw.githack.com/w3c/dpub-aria/main/index.html -o gh-pages/index.html -f  --retry 3
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GH_TOKEN
        keep-history: true
        local-dir: gh-pages
        on:
          branch: main