# netlify.toml
# Basic configuration for a Netlify deployment
[build]
  publish = "" # Directory to publish
  command = "respec -s index.html -o index.html --localhost; respec -s accname/index.html -o accname/index.html --localhost; respec -s core-aam/index.html -o core-aam/index.html --localhost; respec -s dpub-aam/index.html -o dpub-aam/index.html --localhost; respec -s dpub-aria/index.html -o dpub-aria/index.html --localhost; respec -s graphics-aam/index.html -o graphics-aam/index.html --localhost; respec -s graphics-aria/index.html -o graphics-aria/index.html --localhost; respec -s svg-aam/index.html -o svg-aam/index.html --localhost; respec -s mathml-aam/index.html -o mathml-aam/index.html --localhost"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview]
  NODE_ENV = "Deploy"

[context.branch-deploy.environment]
  NODE_ENV = "development"