language: node_js
branches:
  only:
    - gh-pages
env:
  global:
    - URL="https://w3c.github.io/html-aria/echidna-manifest.txt"
    - DECISION="https://lists.w3.org/Archives/Public/public-html-admin/2015May/0021.html"
    - secure: GCoNiJ83LqT6HxuSFPXg0yHBbNxvTVJqzMjubbeU0W+zFUe+C45DoY5EH8tfuNivJbw+SzjoKHYHNSMLsqMaZ9wl1SYkcfbM/HIdkUF6HpXZtxblFCqj7srThSuhbSkzPNodSmwCmjNraKBmqtk95+wl4Ck9wF/d4aFJhyPT4nxtkErIH5fhcJPAeJ9Ui8VuQSrEy9k4VNZU8ylRSoLOSqClHtlpVfhHBITNeoIVzByT6Yp5lwWV4DL8bcCzYnyBLYh2e09POF+tnL/dGkbm5E4GvSFaglZM9mbmb5SLH0y7i21WI7LKtir4G831p1tBQGRejZ/P2e8vgveizsWxWxGL/VrJR9lgJqCjppLmm6rfcKF3lR34PzYRPE+IzJ63HOOysuESKAXq4orCzdP64pooN75JnOQV+baYVJV78abmeA1epGqLOaRcMRreWf/2U+jvzYMqfH7lNP74c82cur9rswfHm14oKhJzbFrJ+CIGO2KqdAlISSm6Hoa7lTARhn5XefmQtSR0hq2q9POmPP5Qo/hH1HeTvriZd1RpeGfEzUAkutUWY19bvAnkxWUlF5PGu0t8zesrn8l54TX4wwHuWeQNoLhU1D0ftnfF6oXH1MmO++EN/qYJAX/QOUY0XO+BV5OU9I0kSJPDuNS6eQBxGrIluNRYXLyhnPdYe0U=
script:
  - echo "Done!"
after_success:
  - curl "https://labs.w3.org/echidna/api/request" --data "url=$URL" --data "decision=$DECISION" --data "token=$TOKEN"
