name: Node CI

on:
  workflow_dispatch:
    inputs:
      branches:
        required: true
        default: stable
  push:
    branches:
      - stable

jobs:
  publish-tr:
    name: Publish to TR from stable branch
    runs-on: ubuntu-latest # only linux supported at present
    steps:
      - uses: actions/checkout@v3
      - uses: w3c/spec-prod@v2
        with:
          W3C_ECHIDNA_TOKEN: ${{ secrets.ECHIDNA_TOKEN }}
          W3C_WG_DECISION_URL: https://lists.w3.org/Archives/Public/public-aria-admin/2018Sep/0011.html
          W3C_BUILD_OVERRIDE: |
            specStatus: WD
