language: node_js

git:
  depth: 3

stages:
  - deploy

jobs:
  include:
    - stage: deploy
      name: "Deploy to gh-pages"
      if: branch = main
      script:
        - mkdir gh-pages
        - git clone --depth=1 --branch=gh-pages https://github.com/w3c/core-aam.git gh-pages
        - cp -R common gh-pages
        - cp -R css gh-pages
        - curl https://labs.w3.org/spec-generator/?type=respec"&"url=https://raw.githack.com/w3c/core-aam/main/index.html -o gh-pages/index.html -f  --retry 3
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GH_TOKEN
        keep-history: true
        local-dir: gh-pages
        on:
          branch: main
