name: accname ED
on:
  push:
    branches:
      - 'main'
    paths:
      - 'common/**'
      - 'accname/**'
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch to accname repo
        run: |
          curl -L -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.W3CGRUNTBOT_TOKEN}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/w3c/accname/actions/workflows/build-from-monorepo.yaml/dispatches \
          -d '{"ref":"gh-pages"}'
  update-accname:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout monorepo
        uses: actions/checkout@v5
        with:
          ref: main
          path: aria
          sparse-checkout: |
            accname
            common
      - name: Copy common
        run: |
          mkdir aria/accname/common
          cp -r aria/common/** aria/accname/common/    
          sed -i 's|\.\./common|common|g' aria/accname/index.html
      - uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: respec
          SOURCE: aria/accname/index.html
          DESTINATION: aria/accname/index.html
          W3C_ECHIDNA_TOKEN: ${{ secrets.ECHIDNA_TOKEN_ACCNAME }}
          W3C_WG_DECISION_URL: https://lists.w3.org/Archives/Public/public-aria-admin/2018Sep/0011.html
          W3C_BUILD_OVERRIDE: |
            specStatus: WD
          ARTIFACT_NAME: accname
      - name: Checkout accname repo
        uses: actions/checkout@v5
        with:
          repository: w3c/accname
          ref: gh-pages
          path: accname
          token: ${{ secrets.W3CGRUNTBOT_TOKEN }}
      - uses: actions/download-artifact@v4
        with:
          name: accname
      - name: Copy files
        run: |
          cp -r aria.gh/aria/accname/** accname/
      - name: Push new files to child repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "ED update"
          git push origin gh-pages
        working-directory: accname
