name: css-aam ED
on:
  push:
    branches:
      - "main"
    paths:
      - "common/**"
      - "css-aam/**"
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch to css-aam repo
        run: |
          curl -L -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.W3CGRUNTBOT_TOKEN}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/w3c/css-aam/actions/workflows/build-from-monorepo.yaml/dispatches \
          -d '{"ref":"gh-pages"}'
  update-css-aam:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout monorepo
        uses: actions/checkout@v5
        with:
          ref: main
          path: aria
          sparse-checkout: |
            css-aam
            common
      - name: Copy common
        run: |
          mkdir aria/css-aam/common
          cp -r aria/common/** aria/css-aam/common/
          sed -i 's|\.\./common|common|g' aria/css-aam/index.html
      - uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: respec
          SOURCE: aria/css-aam/index.html
          DESTINATION: aria/css-aam/index.html
          W3C_ECHIDNA_TOKEN: ${{ secrets.ECHIDNA_TOKEN_HTML_AAM }}
          W3C_WG_DECISION_URL: https://lists.w3.org/Archives/Public/public-aria-admin/2018Sep/0011.html
          # W3C_NOTIFICATIONS_CC: "${{ secrets.CC }}"
          W3C_BUILD_OVERRIDE: |
            specStatus: WD
          ARTIFACT_NAME: css-aam
      - name: Checkout css-aam repo
        uses: actions/checkout@v5
        with:
          repository: w3c/css-aam
          ref: gh-pages
          path: css-aam
          token: ${{ secrets.W3CGRUNTBOT_TOKEN }}
      - uses: actions/download-artifact@v4
        with:
          name: css-aam
      - name: Copy files
        run: |
          cp -r aria.gh/aria/css-aam/** css-aam/
      - name: Push new files to child repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "ED update"
          git push origin gh-pages
        working-directory: css-aam
