name: dpub-aria ED
on:
  push:
    branches:
      - 'main'
    paths:
      - 'common/**'
      - 'dpub-aria/**'
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch to dpub-aria repo
        run: |
          curl -L -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.W3CGRUNTBOT_TOKEN}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/w3c/dpub-aria/actions/workflows/build-from-monorepo.yaml/dispatches \
          -d '{"ref":"gh-pages"}'
  update-dpub-aria:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout monorepo
        uses: actions/checkout@v5
        with:
          ref: main
          path: aria
          sparse-checkout: |
            dpub-aria
            common
      - name: Copy common
        run: |
          mkdir aria/dpub-aria/common
          cp -r aria/common/** aria/dpub-aria/common/
          sed -i 's|\.\./common|common|g' aria/dpub-aria/index.html
      - uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: respec
          SOURCE: aria/dpub-aria/index.html
          DESTINATION: aria/dpub-aria/index.html
          W3C_ECHIDNA_TOKEN: ${{ secrets.ECHIDNA_TOKEN_DPUB_ARIA }}
          W3C_WG_DECISION_URL: https://lists.w3.org/Archives/Public/public-aria-admin/2018Sep/0011.html
          W3C_BUILD_OVERRIDE: |
            specStatus: WD
            shortName: dpub-aria-1.2
          ARTIFACT_NAME: dpub-aria
      - name: Checkout dpub-aria repo
        uses: actions/checkout@v5
        with:
          repository: w3c/dpub-aria
          ref: gh-pages
          path: dpub-aria
          token: ${{ secrets.W3CGRUNTBOT_TOKEN }}
      - uses: actions/download-artifact@v4
        with:
          name: dpub-aria
      - name: Copy files
        run: |
          cp -r aria.gh/aria/dpub-aria/** dpub-aria/
      - name: Push new files to child repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "ED update"
          git push origin gh-pages
        working-directory: dpub-aria
