name: mathml-aam ED
on:
  push:
    branches:
      - 'main'
    paths:
      - 'common/**'
      - 'mathml-aam/**'
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch to mathml-aam repo
        run: |
          curl -L -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.W3CGRUNTBOT_TOKEN}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/w3c/mathml-aam/actions/workflows/build-from-monorepo.yaml/dispatches \
          -d '{"ref":"gh-pages"}'
  update-mathml-aam:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout monorepo
        uses: actions/checkout@v6
        with:
          ref: main
          path: aria
          sparse-checkout: |
            mathml-aam
            common
      - uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: respec
          SOURCE: aria/mathml-aam/index.html
          DESTINATION: aria/mathml-aam/index.html
          ARTIFACT_NAME: mathml-aam
      - name: Checkout mathml-aam repo
        uses: actions/checkout@v6
        with:
          repository: w3c/mathml-aam
          ref: gh-pages
          path: mathml-aam
          token: ${{ secrets.W3CGRUNTBOT_TOKEN }}
      - uses: actions/download-artifact@v7
        with:
          name: mathml-aam
          path: mathml-aam/
    #   - name: Copy files
    #     run: |
    #       cp -r aria/common mathml-aam
    #       cp -r aria/mathml-aam .
      - name: Push new files to child repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Sync from monorepo"
          git push origin gh-pages
        working-directory: mathml-aam
