name: Prettier
# minimally modified from https://github.com/creyD/prettier_action#example-2-using-the-only_changed-or-same_commit-option-on-pr

on:
  pull_request:
    branches: 
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          fetch-depth: 0

      - name: Check if PR is from a fork
        id: check_fork
        run: echo "::set-output name=is_fork::${{ github.event.pull_request.head.repo.fork }}"

      - name: Prettify code
        id: prettify
        uses: creyD/prettier_action@v4.6
        with:
          prettier_options: --write **/index.html --print-width 200
          only_changed: True
          commit_message: "chore: prettier"
        continue-on-error: true

      - name: Handle commit failure
        if: ${{ steps.prettify.outcome == 'failure' && steps.check_fork.outputs.is_fork == 'true' }}
        run: echo "Please run prettier locally"
