name: svg-aam ED
on:
  push:
    branches:
      - 'main'
    paths:
      - 'common/**'
      - 'svg-aam/**'
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch to svg-aam repo
        run: |
          curl -L -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.W3CGRUNTBOT_TOKEN}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/w3c/svg-aam/actions/workflows/build-from-monorepo.yaml/dispatches \
          -d '{"ref":"gh-pages"}'
  update-svg-aam:
    name: Update Editors Draft and Publish to TR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout monorepo
        uses: actions/checkout@v6
        with:
          ref: main
          path: aria
          sparse-checkout: |
            svg-aam
            common
      - name: Copy common
        run: |
          mkdir aria/svg-aam/common
          cp -r aria/common/** aria/svg-aam/common/    
          sed -i 's|\.\./common|common|g' aria/svg-aam/index.html
      - uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: respec
          SOURCE: aria/svg-aam/index.html
          DESTINATION: aria/svg-aam/index.html
          W3C_ECHIDNA_TOKEN: ${{ secrets.ECHIDNA_TOKEN_CORE_AAM }}
          W3C_WG_DECISION_URL: https://lists.w3.org/Archives/Public/public-aria-admin/2018Sep/0011.html
          W3C_BUILD_OVERRIDE: |
            specStatus: WD
          ARTIFACT_NAME: svg-aam
      - name: Checkout svg-aam repo
        uses: actions/checkout@v6
        with:
          repository: w3c/svg-aam
          ref: gh-pages
          path: svg-aam
          token: ${{ secrets.W3CGRUNTBOT_TOKEN }}
      - uses: actions/download-artifact@v7
        with:
          name: svg-aam
      - name: Copy files
        run: |
          cp -r index.html svg-aam/
      - name: Push new files to child repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "ED update"
          git push origin gh-pages
        working-directory: svg-aam

